# Generated by Django 4.1.5 on 2023-04-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('card_name', models.CharField(max_length=50)),
                ('card_photo', models.ImageField(default='default.jpg', upload_to='cards/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_size', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_fio', models.CharField(max_length=200, verbose_name='Имя')),
                ('order_phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('order_email', models.CharField(max_length=200, verbose_name='Email')),
                ('order_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография для картины')),
                ('size', models.ManyToManyField(blank=True, to='goods.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
