# Generated by Django 4.1.5 on 2023-03-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_photo',
            field=models.ImageField(upload_to='cards/images/'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_price', models.CharField(max_length=50)),
                ('picture_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.size')),
            ],
        ),
    ]
