# Generated by Django 4.1.5 on 2023-03-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_size_cards_is_published_cards_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_fio', models.CharField(max_length=200)),
                ('order_phone', models.CharField(max_length=12)),
                ('order_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
