# Generated by Django 4.1.5 on 2023-03-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_order_alter_cards_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
